export type CaseCategory = 'animal' | 'space' | 'food' | 'sport';

export const CASE_ITEM_NAME_MAP: Record<CaseCategory, Record<string, string>> = {
  animal: {
    mouse: 'StatTrak MAC-10 | Neon Rider',
    rabbit: 'Desert Eagle | Blaze',
    frog: 'M4A4 | The Emperor',
    chicken: 'AK-47 | Neon Revolution',
    pig: 'USP-S | Neo-Noir',
    panda: 'AK-47 | The Empress',
    fox: 'StatTrak Glock-18 | Vogue',
    raccoon: 'Karambit | Vanilla',
    lion: 'Five-SeveN | Coolant',
    tiger: 'Talon Knife | Marble Fade',
    unicorn: 'P2000 | Heckler & Koch',
    dragon: 'Beretta 98 | M1911 ',
    't-rex': 'Supernova | Benelli',
    crown: 'TEC-DC9 | Intratec ',
  },

  space: {
    star: 'StatTrak MAC-10 | Neon Rider',
    moon: 'Desert Eagle | Blaze',
    comet: 'M4A4 | The Emperor',
    ufo: 'AK-47 | Neon Revolution',
    earth: 'USP-S | Neo-Noir',
    saturn: 'AK-47 | The Empress',
    galaxy: 'StatTrak Glock-18 | Vogue',
    rocket: 'Karambit | Vanilla',
    alien: 'Five-SeveN | Coolant',
    'glowing star': 'Talon Knife | Marble Fade',
    dizzy: 'P2000 | Heckler & Koch',
    'shooting star': 'Beretta 98 | M1911 ',
    telescope: 'Supernova | Benelli ',
    sun: 'TEC-DC9 | Intratec',
  },

  food: {
    apple: 'StatTrak MAC-10 | Neon Rider',
    banana: 'Desert Eagle | Blaze',
    bread: 'M4A4 | The Emperor',
    carrot: 'AK-47 | Neon Revolution',
    cucumber: 'USP-S | Neo-Noir',
    pizza: 'AK-47 | The Empress',
    burger: 'StatTrak Glock-18 | Vogue',
    taco: 'Karambit | Vanilla',
    cake: 'Five-SeveN | Coolant',
    sushi: 'Talon Knife | Marble Fade',
    lobster: 'P2000 | Heckler & Koch',
    champagne: 'Beretta 98 | M1911 ',
    'birthday cake': 'Supernova | Benelli',
    diamond: 'TEC-DC9 | Intratec ',
  },

  sport: {
    'soccer ball': 'StatTrak MAC-10 | Neon Rider',
    basketball: 'Desert Eagle | Blaze',
    football: 'M4A4 | The Emperor',
    baseball: 'AK-47 | Neon Revolution',
    tennis: 'USP-S | Neo-Noir',
    volleyball: 'AK-47 | The Empress',
    'ping pong': 'StatTrak Glock-18 | Vogue',
    boxing: 'Karambit | Vanilla',
    'gold medal': 'Five-SeveN | Coolant',
    trophy: 'Talon Knife | Marble Fade',
    'military medal': 'P2000 | Heckler & Koch',
    crown: 'Beretta 98 | M1911 ',
    medal: 'Supernova | Benelli',
    lightning: ' TEC-DC9 | Intratec',
  },
};
